%define SEGMENT_KERNEL 0x1000 >> 4

%define SYS_INT 0xff
%define SYS_INT_PRINT_CHAR 0x00
%define SYS_INT_PRINT_STRING 0x01
%define SYS_INT_PRINT_HEX 0x02
%define SYS_INT_GET_KEYSTROKE 0x03
%define SYS_INT_CLEAR_SCREEN 0x04
%define SYS_INT_REBOOT 0x05
