; Kernel at 4KiB
;%define ADDRESS_KERNEL 0x1000
%define ADDRESS_KERNEL 0
;%define ADDRESS_KERNEL 0x200000
; Stack goes down from 640KiB
;%define ADDRESS_STACK 0x7FFFF 
%define ADDRESS_STACK 0xFFFF 
%define SEGMENT_KERNEL 0x1000 >> 4

%define SYS_INT 0x30
%define SYS_INT_PRINT_CHAR 0x00
%define SYS_INT_PRINT_STRING 0x01
%define SYS_INT_PRINT_HEX 0x02
%define SYS_INT_GET_KEYSTROKE 0x03
%define SYS_INT_GET_PRESSED_ASCII 0x07
%define SYS_INT_CLEAR_SCREEN 0x04
%define SYS_INT_REBOOT 0x05

%define TERMINAL_MODE_80x25 1
%define TERMINAL_MODE_80x50 2

%define TERMINAL_FOREGROUND_BLACK 0x00
%define TERMINAL_FOREGROUND_BLUE 0x01
%define TERMINAL_FOREGROUND_GREEN 0x02
%define TERMINAL_FOREGROUND_CYAN 0x03
%define TERMINAL_FOREGROUND_RED 0x04
%define TERMINAL_FOREGROUND_MAGENTA 0x05
%define TERMINAL_FOREGROUND_BROWN 0x06
%define TERMINAL_FOREGROUND_GRAY 0x07

%define TERMINAL_BACKGROUND_BLACK 0x00
%define TERMINAL_BACKGROUND_BLUE 0x10
%define TERMINAL_BACKGROUND_GREEN 0x20
%define TERMINAL_BACKGROUND_CYAN 0x30
%define TERMINAL_BACKGROUND_RED 0x40
%define TERMINAL_BACKGROUND_MAGENTA 0x50
%define TERMINAL_BACKGROUND_BROWN 0x60
%define TERMINAL_BACKGROUND_WHITE 0x70

%define TERMINAL_ATTRIB_LIGHT 0x08
%define TERMINAL_ATTRIB_BLINKING 0x80
